# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testkube < Formula
  desc "Testkube - your somewhat opinionated and friendly Kubernetes testing framework!"
  homepage "https://testkube.io"
  version "0.11.2-dev3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kubeshop/testkube/releases/download/v0.11.2-dev3/testkube_0.11.2-dev3_macOS_arm64.tar.gz"
      sha256 "01ce361e3ce9bcfad370ab58ac90981261c5021440ced10557c33f75f45a178f"

      def install
        bin.install "kubectl-testkube"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/testkube/releases/download/v0.11.2-dev3/testkube_0.11.2-dev3_macOS_x86_64.tar.gz"
      sha256 "79ef6b37ccf19f19532fb5ee4810a8f7c81f3274c8f0d3b9b89694f6375e56e3"

      def install
        bin.install "kubectl-testkube"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeshop/testkube/releases/download/v0.11.2-dev3/testkube_0.11.2-dev3_Linux_arm64.tar.gz"
      sha256 "56aa4541fedf32e839fae70d34fe15029cc493a368d23a3a8553e4b58429da15"

      def install
        bin.install "kubectl-testkube"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/testkube/releases/download/v0.11.2-dev3/testkube_0.11.2-dev3_Linux_x86_64.tar.gz"
      sha256 "a56c411048792d3bc1b3a4a78ec9a4490b0f6cd09c80be61a02668083c929bf4"

      def install
        bin.install "kubectl-testkube"
      end
    end
  end
end
